import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { Card } from '../components/ui/Card';
import { EmptyState } from '../components/ui/EmptyState';
import { Input, Select, Textarea } from '../components/ui/Input';
import { Table, TBody, TD, TH, THead, TR } from '../components/ui/Table';
export function DesignSystemPage() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("header", { className: "space-y-2", children: [_jsx("div", { className: "font-sans text-adminLabel uppercase tracking-[0.25em] text-admin-muted", children: "Living Styleguide" }), _jsx("h1", { className: "font-sans text-adminTitle font-semibold text-admin-text", children: "Design system admin" })] }), _jsxs("div", { className: "grid gap-6 xl:grid-cols-2", children: [_jsxs(Card, { className: "space-y-4", children: [_jsx("h2", { className: "font-sans text-adminHeading font-semibold text-admin-text", children: "Buttons" }), _jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsx(Button, { children: "Primary" }), _jsx(Button, { variant: "outline", children: "Outline" }), _jsx(Button, { variant: "ghost", children: "Ghost" }), _jsx(Button, { variant: "danger", children: "Danger" })] })] }), _jsxs(Card, { className: "space-y-4", children: [_jsx("h2", { className: "font-sans text-adminHeading font-semibold text-admin-text", children: "Badges" }), _jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsx(Badge, { children: "Attiva" }), _jsx(Badge, { tone: "success", children: "Approvata" }), _jsx(Badge, { tone: "danger", children: "Errore" }), _jsx(Badge, { tone: "muted", children: "Bozza" })] })] }), _jsxs(Card, { className: "space-y-4", children: [_jsx("h2", { className: "font-sans text-adminHeading font-semibold text-admin-text", children: "Form" }), _jsx(Input, { placeholder: "Titolo missione" }), _jsxs(Select, { defaultValue: "gallipoli", children: [_jsx("option", { value: "gallipoli", children: "Gallipoli" }), _jsx("option", { value: "lecce", children: "Lecce" })] }), _jsx(Textarea, { className: "h-32", placeholder: "Descrizione o brief" })] }), _jsx(EmptyState, { title: "Nessun elemento. Inizia creandone uno.", description: "Questo stato mostra il vuoto standard del pannello admin.", actionLabel: "Crea elemento" }), _jsxs(Card, { className: "xl:col-span-2", children: [_jsx("h2", { className: "mb-4 font-sans text-adminHeading font-semibold text-admin-text", children: "Tabella" }), _jsx("div", { className: "overflow-x-auto", children: _jsxs(Table, { children: [_jsx(THead, { children: _jsxs("tr", { children: [_jsx(TH, { children: "Nome" }), _jsx(TH, { children: "Stato" }), _jsx(TH, { children: "Ultimo aggiornamento" })] }) }), _jsxs(TBody, { children: [_jsxs(TR, { children: [_jsx(TD, { children: "Il passaggio" }), _jsx(TD, { children: _jsx(Badge, { tone: "success", children: "Attiva" }) }), _jsx(TD, { children: "19/04/2026" })] }), _jsxs(TR, { children: [_jsx(TD, { children: "Dove non guarderesti" }), _jsx(TD, { children: _jsx(Badge, { tone: "muted", children: "Bozza" }) }), _jsx(TD, { children: "18/04/2026" })] })] })] }) })] })] })] }));
}
